version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/1_schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ../db/2_seed.sql:/docker-entrypoint-initdb.d/2_seed.sql

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  postgres_data: